name: build and test [Python 3.8]

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install blake
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements.txt
      
      - name: run linter [blake]
        run: blake .
        
      - name: run unit tests [pytest]
        run: pytest -v
